version: '3'

services:
  django:
    build: .
    restart: always
    command: >
      bash -c "
        python manage.py makemigrations &&
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8080
      "
    depends_on:
      - database
    volumes:
      - .:/app/
    ports:
      - 8080:8080

  database:
    image: postgres
    restart: always
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - reticules-database:/var/lib/postgresql/data

volumes:
  reticules-database:
