# Generated by Django 4.1.2 on 2022-10-06 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reticules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20)),
                ('semester', models.PositiveSmallIntegerField()),
                ('theoretical_hours', models.PositiveSmallIntegerField()),
                ('practical_hours', models.PositiveSmallIntegerField()),
                ('reticule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='reticules.reticule')),
            ],
        ),
    ]
